default_arm_joint_pos: [0, -1.57, 2.88, 0.26, 0]

min_arm_joint_pos: [-2.61,    0, -2.87, -1.51, -1.34, -2.79]
max_arm_joint_pos: [ 2.61, 2.96,     0,  1.51,  1.34,  2.79]

min_arm_joint_vel: [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0]
max_arm_joint_vel: [ 1.0,  1.0,  1.0,  1.0,  1.0,  1.0]

min_body_vel: [-0.5, -0.5, -0.5]
max_body_vel: [ 0.5,  0.5,  0.5]

# PD of Body
kpPos: [200, 200, 1000]     # PD parameter of body position 
kdPos: [50, 70, 50]      
kpAng: [500, 500, 150]     # PD parameter of body angular 
kdAng: [50, 50, 50]      
kpSw: [300, 300, 300]      # PD parameter of swing leg
kdSw: [30, 30, 30]

# PD of Arm
kpEePos: [300, 300, 300]   # PD parameter of EE position
kdEePos: [30, 30, 30]
kpEeAng: [350, 350, 350]   # PD parameter of EE angular
kdEeAng: [35, 35, 35]
kpArmJ: [500, 500, 500, 500, 500]   # PD parameter of arm joint
kdArmJ: [50, 50, 50, 50, 50]


# weight of QP
wBlinear: 1
wBangle: 1
wSw: 1
wElinear: 1
wEangle: 1
wArmJ: 1